name: Android Build

on:
  workflow_dispatch:

env:
  HAXE_VERSION: 4.3.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Build
        run: haxelib run lime build android -release            ${{ inputs.cacheLibrariesPath }}

      - name: Restore existing build cache
        id: load-cache
        uses: actions/cache@v3
        with:
          key: ${{ inputs.cachePath }}
          path: |
            export/release/android/haxe/
            export/release/android/obj/
          restore-keys: |
            ${{ inputs.cachePath }}

      - name: Configure Android
        env:
          PLAYSTORE_FIREBASE: ${{ secrets.PLAYSTORE_FIREBASE }}
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          printf '%s' "$PLAYSTORE_FIREBASE" > ./setup/google-services.json

      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      - name: Upload debugging symbols (Android)
        run: sh ./setup/firebase_spell.sh

      - name: Sign APK
        env:
          OUT_DIR: ./export/release/android/bin/app/build/outputs/apk/release/
          SIGNING_KEY: ${{ secrets.MIKOLKA_PASSWORD }}
          SIGNING_ALIAS: pslice
          SIGNING_FILE: ${{ secrets.MIKOLKA_KEYSTORE }}
        run: |
          rm -f ./key.keystore
          echo $SIGNING_FILE | base64 -d > ./key.keystore
          sha256sum ./key.keystore

          mv "${OUT_DIR}PSliceEngine-release.apk" "${OUT_DIR}PSliceEngine-unsigned.apk"

          $ANDROID_HOME/build-tools/35.0.1/zipalign -P 16 -f -v 4 \
            "${OUT_DIR}PSliceEngine-unsigned.apk" \
            "${OUT_DIR}PSliceEngine-release.apk" > /dev/null

          $ANDROID_HOME/build-tools/35.0.1/apksigner sign \
            --ks key.keystore \
            --ks-key-alias $SIGNING_ALIAS \
            --ks-pass "env:SIGNING_KEY" \
            --key-pass "env:SIGNING_KEY" \
            "${OUT_DIR}PSliceEngine-release.apk"

          rm "${OUT_DIR}PSliceEngine-unsigned.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error

      - name: Clear existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "${{ inputs.cachePath }}") {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
            }

      - name: Upload new cache
        uses: actions/cache@v3
        with:
          key: ${{ inputs.cachePath }}
          path: |
            export/release/android/haxe/
            export/release/android/obj/
          restore-keys: |
            ${{ inputs.cachePath }}
